# Number of nodes to start:
NODES_COUNT = 3

VAGRANTFILE_API_VERSION = "2"
# set docker as the default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
# disable parallellism so that the containers come up in order
ENV['VAGRANT_NO_PARALLEL'] = "1"
ENV['FORWARD_DOCKER_PORTS'] = "1"
# minor hack enabling to run the image and configuration trigger just once
ENV['VAGRANT_EXPERIMENTAL']="typed_triggers"

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

# Names of Docker images built:
CLIENT_IMAGE  = "node_election:latest"
LOOKUP_IMAGE  = "node_lookup:latest"

# Node definitions
NODE  = { 
          :dir => "client",
          :name_prefix => "node-",  
          :subnet => "10.0.1.",
          :ip_offset => 10, 
          :image => CLIENT_IMAGE,
          :lb_config_file => "client/config.conf"
        }

# Lookup definition
LOOKUP = {
    :dir => "lookup",
    :name => "node-lookup",
    :ip_addr => "10.0.1.111",
    :image => LOOKUP_IMAGE,
    :lb_config_file => "lookup/config.conf"
}


# Common configuration
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # Before the 'vagrant up' command is started, build docker images:
  config.trigger.before :up, type: :command do |trigger|
    trigger.name = "Build docker images and configuration files"
    trigger.ruby do |env, machine|
      # --- start of Ruby script ---
      puts "Building nodes configuration"
      File.delete(LOOKUP[:lb_config_file]) if File.exist?(LOOKUP[:lb_config_file])
      file = File.new(LOOKUP[:lb_config_file], 'w')
      file.puts "#{NODES_COUNT}"
      file.close

      File.delete(NODE[:lb_config_file]) if File.exist?(NODE[:lb_config_file])
      file = File.new(NODE[:lb_config_file], 'w')
      file.puts "#{NODES_COUNT}"
      file.close

      puts "Building node image:"
      `docker build -t "#{NODE[:image]}" #{NODE[:dir]}`
      `docker build -t "#{LOOKUP[:image]}" #{LOOKUP[:dir]}`
      # --- end of Ruby script ---

    end
  end

  config.vm.define LOOKUP[:name] do |s|
    s.vm.network "private_network", ip: LOOKUP[:ip_addr]
    s.vm.network "forwarded_port", guest: 5000, host: 8080, host_ip: "0.0.0.0"
    s.vm.hostname = LOOKUP[:name]
    s.vm.provider "docker" do |d|
      d.image = LOOKUP[:image]
      d.name = LOOKUP[:name]
    end
    s.vm.post_up_message = "Node #{LOOKUP[:name]} up and running. You can access the node with 'vagrant ssh #{LOOKUP[:name]}'}"
  end

  # Definition of N nodes
  (1..NODES_COUNT).each do |i|
    node_ip_addr = "#{NODE[:subnet]}#{NODE[:ip_offset] + i}"
    node_name = "#{NODE[:name_prefix]}#{i}"
    config.vm.define node_name do |s|
        s.vm.network :private_network, ip: node_ip_addr
        s.vm.hostname = node_name

        s.vm.provider "docker" do |d|
            d.image = NODE[:image]
            d.name = node_name
            d.env = {
                "NodesCount": NODES_COUNT
            }
        end

        s.vm.post_up_message = "Node #{node_name} up and running."
    end
  end

end

# EOF
