#
# *** Demo 3
# Create N backend nodes and 1 frontend node working as a load-balancer.
#

# Number of backends to start:
NODES_COUNT = 3
VAGRANTFILE_API_VERSION = "2"
# set docker as the default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
# disable parallellism so that the containers come up in order
ENV['VAGRANT_NO_PARALLEL'] = "1"
ENV['FORWARD_DOCKER_PORTS'] = "1"
# minor hack enabling to run the image and configuration trigger just once
ENV['VAGRANT_EXPERIMENTAL']="typed_triggers"

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

# Names of Docker images built:
CLIENT_IMAGE  = "node_election:latest"

# Node definitions
NODE  = { 
          :dir => "client",
          :name_prefix => "client-",  
          :subnet => "10.0.1.",
          :ip_offset => 10, 
          :image => CLIENT_IMAGE,
          :lb_config_file => "client/config.conf" # generated config.
        }

# Common configuration
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # Before the 'vagrant up' command is started, build docker images:
  config.trigger.before :up, type: :command do |trigger|
    trigger.name = "Build docker images and configuration files"
    trigger.ruby do |env, machine|
      # --- start of Ruby script ---
      puts "Building nodes configuration"
      File.delete(NODE[:lb_config_file]) if File.exist?(NODE[:lb_config_file])
      file = File.new(NODE[:lb_config_file], 'w')
      (1..NODES_COUNT).each do |i|
          node_name = "#{NODE[:name_prefix]}#{i}"
          node_ip = "#{NODE[:subnet]}#{NODE[:ip_offset] + i}"
          file.puts "#{node_name} #{node_ip}"
      end
      file.close

      puts "Building node image:"
      `docker build -t "#{NODE[:image]}" #{NODE[:dir]}`
      # --- end of Ruby script ---

    end
  end

  # Definition of N nodes
  (1..NODES_COUNT).each do |i|
    node_ip_addr = "#{NODE[:subnet]}#{NODE[:ip_offset] + i}"
    node_name = "#{NODE[:name_prefix]}#{i}"
    config.vm.define node_name do |s|
        s.vm.network :private_network, ip: node_ip_addr
        s.vm.hostname = node_name

        s.vm.provider "docker" do |d|
            d.image = NODE[:image]
            d.name = node_name
            # d.has_ssh = true
            d.env = {
                "ID": node_name,
            }
        end

        s.vm.post_up_message = "Node #{node_name} up and running."
    end
  end

end

# EOF
