openapi: 3.0.0

info:
  title: KIV-DS
  description: Distributed Cache
  version: 1.0.0

tags:
  - name: Cache

paths:
  /cache:
    get:
      summary: Get key value
      tags:
        - Cache
      description: Get key value
      operationId: get_val
      parameters:
        - in: query
          name: key
          schema:
            type: string
          description: Key value
      responses:
        '200':
          description: OK
        '400':
          description: Invalid key parameter
        '404':
          description: No value exists for entered key

    delete:
      summary: Delete value
      tags:
        - Cache
      description: Delete value
      operationId: delete_val
      parameters:
        - in: query
          name: key
          schema:
            type: string
          description: Key value
      responses:
        '200':
          description: OK
        '400':
          description: Invalid key parameter
        '404':
          description: No value exists for entered key

    put:
      summary: Add new key-value record
      tags:
        - Cache
      description: Add new key-value record
      operationId: put_key_val
      parameters:
        - in: query
          name: key
          schema:
            type: string
          description: Key value
        - in: query
          name: value
          schema:
            type: string
          description: Value which is stored in key
      responses:
        '200':
          description: OK
        '400':
          description: Invalid key or value parameters